FROM python:3.12-slim

# Define build arguments for the proxy
ARG http_proxy

# Set environment variables
ENV http_proxy=$http_proxy
ENV https_proxy=$http_proxy

RUN pip install pyftpdlib

# Create the FTP user's home directory
RUN mkdir -p /home/ftpuser

# Expose the FTP port
EXPOSE 21

# Run pyftpdlib with environment variables
RUN echo "$FTP_USER" > /home/ftpuser/ftpuser.txt && echo "$FTP_PASS" > /home/ftpuser/ftppass.txt

CMD ["python", "-m", "pyftpdlib", "-i", "0.0.0.0", "-p", "21", "--username", "$FTP_USER", "--password", "$FTP_PASS", "--directory", "/home/ftpuser"]
