version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app-dev
    container_name: my-app-dev
    ports:
      - "1337:5000"
    volumes:
      - shared_volume:/usr/src/app/shared\
    environment:
      - ENVIRONMENT=development
      - WAF=${WAF}
      - NGINX=${NGINX}
      - USE_REMOTE=${USE_REMOTE}
      - DNS_HOSTNAME=${DNS_HOSTNAME} # e.g. DNS_HOSTNAME=/usr/src/app/shared/myzonefile.db
      - UPDATE_TIME=${UPDATE_TIME}
    restart: unless-stopped

  sftp:
    build:
      context: .
      dockerfile: Dockerfile.sftp
      args:
        DNS_SERVER_SSH_PUBKEY: ${DNS_SERVER_SSH_PUBKEY}
    image: my-sftp-dev
    container_name: my-sftp-dev
    ports:
      - "2222:22"
    volumes:
      - shared_volume:/chroot/upload
    restart: unless-stopped

volumes:
  shared_volume:
    driver: local