services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wams-prod
    container_name: wams-prod
    ports:
      - "1337:5000"
    volumes:
      - dns_zonefiles_volume:/usr/src/app/shared
      - db_and_backups_volume:/appdata
    environment:
      - ENVIRONMENT=production
      - WAF=${WAF}
      - NGINX=${NGINX}
      - USE_REMOTE=${USE_REMOTE}
      - DNS_HOSTNAME=${DNS_HOSTNAME}
      - UPDATE_TIME=${UPDATE_TIME}
    # restart: unless-stopped

  sftp:
    build:
      context: .
      dockerfile: Dockerfile.sftp
      args:
        DNS_SERVER_SSH_PUBKEY: ${DNS_SERVER_SSH_PUBKEY}
    image: wams-sftp-prod
    container_name: wams-sftp-prod
    ports:
      - "2222:22"
    volumes:
      - dns_zonefiles_volume:/chroot/upload
    restart: unless-stopped

volumes:
  dns_zonefiles_volume:
    driver: local