services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    image: wams-dev
    container_name: wams-dev
    ports:
      - "1337:5000"
    volumes:
      - dns_zonefiles_volume:/usr/src/app/shared
      - db_and_backups_volume:/appdata
    environment:
      - ENVIRONMENT=development
      - WAF=${WAF}
      - DNS_HOSTNAME=${DNS_HOSTNAME}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - NGINX=${NGINX}
      - UPDATE_TIME=${UPDATE_TIME}
      - DATA_PATH=${DATA_PATH}
      - SHARED_PATH=${SHARED_PATH}
      - BACKUP_FOLDER=${BACKUP_FOLDER}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_SERVER=${LDAP_SERVER}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    restart: unless-stopped

  sftp:
    build:
      context: .
      dockerfile: Dockerfile.sftp
      args:
        DNS_SERVER_SSH_PUBKEY: ${DNS_SERVER_SSH_PUBKEY}
    image: wams-sftp-dev
    container_name: wams-sftp-dev
    ports:
      - "2222:22"
    volumes:
      - dns_zonefiles_volume:/chroot/upload
    restart: unless-stopped

volumes:
  db_and_backups_volume:
    driver: local
  dns_zonefiles_volume:
    driver: local