FROM python:3.12-slim-buster

RUN pip install pyftpdlib

# Create the FTP user's home directory
RUN mkdir -p /home/ftpuser

# Expose the FTP port
EXPOSE 21

# Set default username and directory (password will be handled in entrypoint)
ENV FTP_USER_NAME=ftpuser
ENV FTP_DIRECTORY=/home/ftpuser

# Copy the entrypoint script
COPY ftp/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Use the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]