"""Compatibility facade for OffSec endpoints and utilities."""

from app.domain.offsec.shared import (
    DB_PATH,
    build_checklist_revision,
    build_report_template_revision,
    get_canonical_checklist_by_key,
    get_canonical_report_template_by_key,
    get_default_report_templates,
    get_default_service_checklists,
    normalize_checklist_template_payload as _normalize_checklist_template_payload,
    normalize_ports as _normalize_ports,
    normalize_report_template_definition as _normalize_report_template_definition,
    normalize_report_template_payload as _normalize_report_template_payload,
    normalize_template_sections as _normalize_template_sections,
    safe_json_load as _safe_json_load,
    serialize_checklist_template as _serialize_checklist_template,
    serialize_report_template as _serialize_report_template,
    to_int as _to_int,
)
from app.integrations.storage.offsec_storage import (
    ALLOWED_IMAGE_EXTENSIONS,
    can_user_access_image as _can_user_access_image,
    cleanup_unreferenced_images as _cleanup_unreferenced_images,
    collect_referenced_image_filenames as _collect_referenced_image_filenames,
    delete_image,
    delete_report,
    extract_image_filenames as _extract_image_filenames,
    extract_image_filenames_from_vulnerabilities as _extract_image_filenames_from_vulnerabilities,
    fetch_image,
    ftp_connect,
    guess_image_mimetype as _guess_image_mimetype,
    save_image,
    save_report,
)
from app.repositories.offsec.offsec_records import (
    enforce_pentest_record_access,
    get_pentest_data_internal,
    get_pentest_row,
    get_pentest_users_internal,
    get_record_details_internal,
)
from app.services.offsec import (
    create_checklist_template,
    create_or_update_pentest_data,
    create_report_template,
    delete_checklist_template,
    delete_generated_report_route,
    delete_pentest_data,
    delete_report_route,
    delete_report_template,
    generate_report,
    get_checklist_templates,
    get_generated_report,
    get_pentest_data,
    get_pentest_image,
    get_pentest_users,
    get_report,
    get_report_templates,
    load_enabled_checklist_templates as _load_enabled_checklist_templates,
    reset_checklist_template_to_canonical,
    reset_report_template_to_canonical,
    update_checklist_template,
    update_report_template,
    upload_pentest_image,
)

__all__ = [
    "ALLOWED_IMAGE_EXTENSIONS",
    "DB_PATH",
    "_can_user_access_image",
    "_cleanup_unreferenced_images",
    "_collect_referenced_image_filenames",
    "_extract_image_filenames",
    "_extract_image_filenames_from_vulnerabilities",
    "_guess_image_mimetype",
    "_load_enabled_checklist_templates",
    "_normalize_checklist_template_payload",
    "_normalize_ports",
    "_normalize_report_template_definition",
    "_normalize_report_template_payload",
    "_normalize_template_sections",
    "_safe_json_load",
    "_serialize_checklist_template",
    "_serialize_report_template",
    "_to_int",
    "build_checklist_revision",
    "build_report_template_revision",
    "create_checklist_template",
    "create_or_update_pentest_data",
    "create_report_template",
    "delete_checklist_template",
    "delete_generated_report_route",
    "delete_image",
    "delete_pentest_data",
    "delete_report",
    "delete_report_route",
    "delete_report_template",
    "enforce_pentest_record_access",
    "fetch_image",
    "ftp_connect",
    "generate_report",
    "get_canonical_checklist_by_key",
    "get_canonical_report_template_by_key",
    "get_checklist_templates",
    "get_default_report_templates",
    "get_default_service_checklists",
    "get_generated_report",
    "get_pentest_data",
    "get_pentest_data_internal",
    "get_pentest_image",
    "get_pentest_row",
    "get_pentest_users",
    "get_pentest_users_internal",
    "get_record_details_internal",
    "get_report",
    "get_report_templates",
    "reset_checklist_template_to_canonical",
    "reset_report_template_to_canonical",
    "save_image",
    "save_report",
    "update_checklist_template",
    "update_report_template",
    "upload_pentest_image",
]
